// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ9CIZfoHgXM57RzM6xeJn7Ewl-DjV3eA',
    appId: '1:490077799513:web:b36f8390b3389b1add1d48',
    messagingSenderId: '490077799513',
    projectId: 'lane-choice',
    authDomain: 'lane-choice.firebaseapp.com',
    storageBucket: 'lane-choice.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE6H6luyqpOz6aOIbQSTvCbXxJjH3BG5g',
    appId: '1:490077799513:android:bc112292b1be6ff9dd1d48',
    messagingSenderId: '490077799513',
    projectId: 'lane-choice',
    storageBucket: 'lane-choice.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAolGmfIyxm-CpCvN0x-w9bjmZxGgUk0Z4',
    appId: '1:490077799513:ios:550f711a8a78c1b5dd1d48',
    messagingSenderId: '490077799513',
    projectId: 'lane-choice',
    storageBucket: 'lane-choice.firebasestorage.app',
    iosBundleId: 'com.example.lanchoiceMvp',
  );
}
